# Site settings
title: Matthew D. Huff's Portfolio
email: matthewhuff89@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Matthew D. Huff is a full-stack web developer who lives to master himself through tech and experience. LOVE-HUSTLE-EVOLVE.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.matthewdhuff.com" # the base hostname & protocol for your site
twitter_username: theinfamoushuff
github_username:  matthewhuff89
linkedin_url: "http://www.linkedin.com/in/matthewdhuff"
# Build settings
markdown: kramdown

