# Site settings
title: Matthew D. Huff's Badass Website
email: matthewhuff89@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my webpage! This is just a little portfolio site for me to show to parties interested in my services as a developer! Have a good time!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.matthewdhuff.com" # the base hostname & protocol for your site
twitter_username: theinfamoushuff
github_username:  matthewhuff89

# Build settings
markdown: kramdown

